# Generated by Django 3.1.5 on 2021-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210220_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_type', models.CharField(max_length=50, null=True)),
                ('fitness_desc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
