# Generated by Django 3.1.5 on 2021-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_member_fitness'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='fitness_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
