# Generated by Django 3.1.5 on 2021-03-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210313_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='member',
            name='plan',
        ),
    ]
