# Generated by Django 3.1.5 on 2021-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_alt_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
