# Generated by Django 3.1.5 on 2021-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_trainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='fitness_price',
            field=models.IntegerField(default=0),
        ),
    ]
