# Generated by Django 3.1.5 on 2021-04-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_fitness_fitness_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='fitness_price',
        ),
    ]
