# Generated by Django 3.1 on 2021-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_fitness_fitness_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
