# Generated by Django 3.1 on 2021-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_fitness_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email_id', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('alt_phone_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
