# Generated by Django 3.1 on 2021-04-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_freetrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetrial',
            name='address',
        ),
    ]
