# Generated by Django 3.1 on 2021-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_freetrial_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email_id', models.EmailField(max_length=50, null=True)),
                ('message', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='freetrial',
            name='email_id',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
